# Generated by Django 5.1.7 on 2025-03-19 01:12

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Status')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('permission', models.JSONField(default=dict, verbose_name='Permission')),
                ('password', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='User Since')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='Updated At')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
            ],
            options={
                'verbose_name_plural': 'Core Users',
                'db_table': 'core_user',
            },
        ),
    ]
