# Generated by Django 5.1.7 on 2025-03-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coreuser_is_active_coreuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Age'),
        ),
    ]
