# Generated by Django 5.1.7 on 2025-03-20 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_coreuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('code', models.CharField(verbose_name='Verification Code')),
                ('used', models.BooleanField(default=False, verbose_name='Used Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Of User')),
            ],
        ),
    ]
