# Generated by Django 5.1.7 on 2025-03-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user_id',
            new_name='user',
        ),
    ]
