# Generated by Django 5.1.7 on 2025-03-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_id_passwordreset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='google_token',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='profile_link',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='coreuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
