# Generated by Django 5.1.7 on 2025-03-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_verify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
        migrations.AddField(
            model_name='verify_email',
            name='activate',
            field=models.BooleanField(default=True, verbose_name='Activate'),
        ),
    ]
