# Generated by Django 5.1.7 on 2025-03-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_passwordreset_activate_verify_email_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='verify_email',
            old_name='user',
            new_name='user_id',
        ),
    ]
